services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: eventess
      POSTGRES_USER: eventess 
      POSTGRES_PASSWORD: eventess
    ports:
      - "5432:5432"
    volumes:
      - db_data_local:/var/lib/postgresql/data

volumes:
  db_data_local:
